site_name: Pukara Culture
theme:
  name: material
  logo: pukara-logo.svg
  features:
  - navigation.tabs
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Culture:
    - Home: index.md
    - Core Values: core-values/index.md
    - How to be a professional: be-professional/be-professional.md
  - Onboarding:
    - Welcome: onboarding/index.md
    - First day: onboarding/first-day.md
  - Engineering:
    - Welcome: engineering/index.md
    - Using Git: engineering/using-git.md
